sudo: false
dist: trusty
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libcunit1-dev
            - gcc-4.9
      env: COMPILER=gcc-4.9
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libcunit1-dev
            - gcc-5
      env: COMPILER=gcc-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - libcunit1-dev
            - clang-3.6
      env: COMPILER=clang-3.6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libcunit1-dev
            - clang-3.7
      env: COMPILER=clang-3.7
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - libcunit1-dev
            - clang-3.8
      env: COMPILER=clang-3.8
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - libcunit1-dev
            - clang-3.9
      env: COMPILER=clang-3.9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - libcunit1-dev
            - clang-4.0
      env: COMPILER=clang-4.0
#   - os: linux
#     compiler: clang
#     addons:
#       apt:
#         sources:
#           - llvm-toolchain-trusty-5.0
#         packages:
#           - libcunit1-dev
#           - clang-5.0
#     env: COMPILER=clang-5.0

before_install:
    - export CC=${COMPILER}

script:
  - make test

